services:
  - type: web
    name: mern-product-store
    env: node
    buildCommand: npm ci && cd frontend && npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
